### ISSUE TITLE
Broken link at https://windowsloop.com/how-to-enable-or-disable-font-smoothing-in-windows/#disable

### ISSUE THREAD

**Issue by mehran554** [Etheryte/right-click-opens-link-in-a-background-tab#4] opened 2024-03-29 19:29 UTC
**Is the affected page a public page?**

If the page is not public I can't help you with your issue. I can't debug what I can't access, sorry.  
To check the checkbox, put an `x` between the brackets below: `[ ]` -> `[x]`

 - [ ] Yes, it is a public page

**Where is the link on that page?**

Please insert either a screenshot or a description of where the link is to help me find it:

**Comment by Etheryte** [comment] 2024-03-30 22:39
@mehran554 Please specify which link on the page is problematic, for example with a screenshot. As far as I can see, they all seem to be working fine.

**Comment by Gennady-G** [comment] 2024-03-31 14:34
Hi @mehran554 !

For me it often opens tab twice on aliexpress.com , but this bug is non-permanent and also I have other extensions which may affect it 🤷‍♂️

![2024-03-31_183455](https://github.com/Etheryte/right-click-opens-link-in-a-background-tab/assets/5569346/fcd5fc83-1724-47de-af4b-bb72e17ee902)

**Comment by Etheryte** [comment] 2024-03-31 15:42
@Gennady-G If you're having an issue, please make sure it stems from this extension, not from others. I can't replicate your issue.

**Comment by Gennady-G** [comment] 2024-03-31 17:05
@Etheryte Hi! Not my thread, only FYI.

**Comment by Etheryte** [comment] 2024-04-04 11:54
Closing as the problem is not reproducible.

**Closed by Etheryte** 2024-04-04 11:54 UTC
